// scripts/handoff-prompt.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadConfig, nextStage, statusReport } from './adhd-state.mjs';

// Resolve the working-memory file (if any) for the stage we are resuming into.
function activeWorkFile(cwd, next) {
  const dir = path.join(cwd, 'project/work');
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return null;
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.md'));
  const stage = next.stage;
  const want = next.milestone ? `m${next.milestone}-${stage}.md` : `${stage}.md`;
  if (files.includes(want)) return want;
  // fallback: match the stage segment, scoped to the correct milestone
  return files.find((f) => {
    const base = f.slice(0, -3);
    const mm = /^m(\d+)-(.+)$/.exec(base);
    if (next.milestone) return Boolean(mm) && Number(mm[1]) === next.milestone && mm[2] === stage;
    return !mm && base === stage;
  }) ?? null;
}

// Extract the open checklist items and the last few log lines from a work file.
function summarizeWork(body) {
  const lines = body.split('\n');
  const open = lines.filter((l) => /^\s*- \[ \]/.test(l)).map((l) => l.trim());
  const logIdx = lines.findIndex((l) => /^##\s+log\b/i.test(l));
  let logLines = [];
  if (logIdx >= 0) {
    const rest = lines.slice(logIdx + 1);
    const nextHead = rest.findIndex((l) => /^##\s/.test(l));
    const section = nextHead >= 0 ? rest.slice(0, nextHead) : rest;
    logLines = section.map((l) => l.trim()).filter(Boolean).slice(-3);
  }
  return { open, logLines };
}

export function handoffPrompt(cwd = process.cwd()) {
  const config = loadConfig(cwd);
  if (!config) {
    return 'No project/config.json found. Run `adhd setup` to begin a new project.';
  }
  const next = nextStage(cwd);
  const where = next.stage +
    (next.milestone ? ` — milestone ${next.milestone}` : '') +
    (next.feature ? ` — feature ${next.feature}` : '');
  const runArg = next.stage;

  const work = activeWorkFile(cwd, next);
  const lines = ['Resume the `adhd` conductor.', ''];
  let n = 1;
  if (work) {
    const { open, logLines } = summarizeWork(fs.readFileSync(path.join(cwd, 'project/work', work), 'utf-8'));
    lines.push(`${n++}. Read \`project/work/${work}\` FIRST — your in-flight working memory for this task.`);
    if (open.length) {
      lines.push('   Left to do:');
      for (const o of open) lines.push(`     ${o}`);
    }
    if (logLines.length) {
      lines.push('   Last progress:');
      for (const l of logLines) lines.push(`     ${l}`);
    }
    lines.push(`${n++}. Then check \`project/parking.md\` — durable parked ideas/details not yet implemented.`);
  } else {
    lines.push(`${n++}. Check \`project/parking.md\` FIRST — durable parked ideas/details not yet implemented.`);
  }
  lines.push(`${n++}. Current position: ${where}`);
  lines.push(`${n++}. Run: adhd ${runArg}${next.milestone ? ` --milestone ${next.milestone}` : ''}`);
  lines.push(
    '',
    'State summary:',
    statusReport(cwd).split('\n').map((l) => '  ' + l).join('\n'),
    '',
    `Generated by adhd handoff-prompt at ${new Date().toISOString()}.`,
  );
  return lines.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  console.log(handoffPrompt(process.cwd()));
}
