// scripts/handoff-prompt.mjs
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadState, nextStage, statusReport } from './adhd-state.mjs';

export function handoffPrompt(cwd = process.cwd()) {
  const state = loadState(cwd);
  if (!state) {
    return 'No project/state.json found. Run `{{command_prefix}}adhd setup` to begin a new project.';
  }
  const next = nextStage(cwd);
  const where = next.stage +
    (next.milestone ? ` — milestone ${next.milestone}` : '') +
    (next.feature ? ` — feature ${next.feature}` : '');
  const runArg = next.stage === 'next-milestone' ? 'milestone-brief' : next.stage;
  return [
    'Resume the `adhd` conductor.',
    '',
    '1. Read `project/notes.md` FIRST — it is the scratchpad from the previous session.',
    `2. Current position: ${where}`,
    `3. Run: {{command_prefix}}adhd ${runArg}`,
    '',
    'State summary:',
    statusReport(cwd).split('\n').map((l) => '  ' + l).join('\n'),
    '',
    `Generated by adhd handoff-prompt at ${new Date().toISOString()}.`,
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  console.log(handoffPrompt(process.cwd()));
}
